#nullable enable

using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace Armada.Architecture.Tests
{
    /// <summary>
    /// Section 6.2 of the design doc: the structural rules that keep Armada.Core pure enough to be
    /// compiled verbatim by the Cloud Code module. These fail the build on purpose. Every one of
    /// them exists because the same mistake cost time on a previous project.
    /// </summary>
    [TestFixture]
    public sealed class CoreAssemblyTests
    {
        [Test]
        public void Core_HasNoEngineReferences()
        {
            Assert.That(File.Exists(RepositoryLayout.CoreAssemblyDefinition), Is.True, "Armada.Core.asmdef is missing.");

            using JsonDocument asmdef = JsonDocument.Parse(File.ReadAllText(RepositoryLayout.CoreAssemblyDefinition));
            JsonElement root = asmdef.RootElement;

            Assert.That(root.GetProperty("name").GetString(), Is.EqualTo("Armada.Core"));
            Assert.That(
                root.TryGetProperty("noEngineReferences", out JsonElement noEngineReferences) && noEngineReferences.GetBoolean(),
                Is.True,
                "Armada.Core must declare noEngineReferences: true. Without it the module cannot compile these sources.");

            JsonElement references = root.GetProperty("references");
            Assert.That(references.GetArrayLength(), Is.EqualTo(0), "Armada.Core must not reference any other assembly.");
        }

        [Test]
        public void Core_DoesNotUseAmbientTimeOrRandom()
        {
            // Ambient time and RNG would make the engine untestable and non-deterministic, and would
            // make client and server disagree. Time arrives as a nowUnixMs parameter; randomness
            // arrives through IRandom.
            (string Pattern, string Explanation)[] banned =
            {
                (@"\bDateTime\s*\.\s*Now\b", "use the nowUnixMs parameter instead of DateTime.Now"),
                (@"\bDateTime\s*\.\s*UtcNow\b", "use the nowUnixMs parameter instead of DateTime.UtcNow"),
                (@"\bDateTimeOffset\s*\.\s*Now\b", "use the nowUnixMs parameter instead of DateTimeOffset.Now"),
                (@"\bDateTimeOffset\s*\.\s*UtcNow\b", "use the nowUnixMs parameter instead of DateTimeOffset.UtcNow"),
                (@"\bEnvironment\s*\.\s*TickCount", "use the nowUnixMs parameter instead of Environment.TickCount"),
                (@"\bStopwatch\b", "Core does not measure wall time"),
                (@"\bnew\s+Random\s*\(", "use the injected IRandom instead of System.Random"),
                (@"\bnew\s+System\s*\.\s*Random\s*\(", "use the injected IRandom instead of System.Random"),
                (@"\bGuid\s*\.\s*NewGuid\s*\(", "identifiers are generated by the caller, not by Core"),
                (@"\bRandomNumberGenerator\b", "randomness only enters Core through IRandom")
            };

            List<string> violations = new List<string>();

            foreach (string file in RepositoryLayout.CoreSourceFiles)
            {
                string code = SourceText.StripCommentsAndLiterals(File.ReadAllText(file));

                foreach ((string pattern, string explanation) in banned)
                {
                    if (Regex.IsMatch(code, pattern))
                    {
                        violations.Add(RepositoryLayout.RelativeToRoot(file) + ": " + explanation);
                    }
                }
            }

            Assert.That(violations, Is.Empty, "Ambient time or randomness in Core:\n" + string.Join("\n", violations));
        }

        [Test]
        public void Core_DoesNotReferenceTheEngineInSource()
        {
            List<string> violations = new List<string>();

            foreach (string file in RepositoryLayout.CoreSourceFiles)
            {
                string code = SourceText.StripCommentsAndLiterals(File.ReadAllText(file));
                if (Regex.IsMatch(code, @"\busing\s+UnityEngine\b") || Regex.IsMatch(code, @"\busing\s+UnityEditor\b"))
                {
                    violations.Add(RepositoryLayout.RelativeToRoot(file));
                }
            }

            Assert.That(violations, Is.Empty, "Core must never reference the engine:\n" + string.Join("\n", violations));
        }

        [Test]
        public void Core_DoesNotPerformIO()
        {
            List<string> violations = new List<string>();

            foreach (string file in RepositoryLayout.CoreSourceFiles)
            {
                string code = SourceText.StripCommentsAndLiterals(File.ReadAllText(file));
                if (Regex.IsMatch(code, @"\busing\s+System\s*\.\s*IO\b")
                    || Regex.IsMatch(code, @"\busing\s+System\s*\.\s*Net\b")
                    || Regex.IsMatch(code, @"\bFile\s*\.\s*(Read|Write|Open|Exists)"))
                {
                    violations.Add(RepositoryLayout.RelativeToRoot(file));
                }
            }

            Assert.That(violations, Is.Empty, "Core must not do I/O:\n" + string.Join("\n", violations));
        }

        [Test]
        public void Core_IsNullableClean()
        {
            // Two halves of the same rule: Unity compiles Core through csc.rsp, CI compiles it
            // through the test .csproj. Both must treat the CS86xx family as errors, which is what
            // closes inherited debt #3 before it can be born.
            Assert.That(File.Exists(RepositoryLayout.CoreCompilerResponseFile), Is.True,
                "Assets/Scripts/Core/csc.rsp is missing: Unity would compile Core without nullable analysis.");

            string rsp = File.ReadAllText(RepositoryLayout.CoreCompilerResponseFile);
            Assert.That(rsp, Does.Contain("-nullable:enable"));
            Assert.That(rsp, Does.Contain("-warnaserror:"));
            Assert.That(rsp, Does.Contain("CS8618"), "CS8618 (uninitialized non-nullable field) must be an error.");

            string testProject = File.ReadAllText(
                Path.Combine(RepositoryLayout.Root, "Tests", "Armada.Core.Tests", "Armada.Core.Tests.csproj"));

            Assert.That(testProject, Does.Contain("<Nullable>enable</Nullable>"));
            Assert.That(testProject, Does.Contain("CS8618"));
        }

        [Test]
        public void Core_DeclaresNullableInEveryFile()
        {
            List<string> violations = new List<string>();

            foreach (string file in RepositoryLayout.CoreSourceFiles)
            {
                string text = File.ReadAllText(file);
                if (!text.Contains("#nullable enable"))
                {
                    violations.Add(RepositoryLayout.RelativeToRoot(file));
                }
            }

            Assert.That(violations, Is.Empty, "Missing #nullable enable:\n" + string.Join("\n", violations));
        }

        [Test]
        public void Core_UsesBracedNamespaces_BecauseUnityCompilesCSharp9()
        {
            // File-scoped namespaces are C# 10. Unity 6.3 LTS compiles C# 9, so a file-scoped
            // namespace builds fine in the headless runner and then breaks the Editor build.
            List<string> violations = new List<string>();

            foreach (string file in RepositoryLayout.CoreSourceFiles)
            {
                string code = SourceText.StripCommentsAndLiterals(File.ReadAllText(file));
                if (Regex.IsMatch(code, @"^\s*namespace\s+[\w\.]+\s*;", RegexOptions.Multiline))
                {
                    violations.Add(RepositoryLayout.RelativeToRoot(file));
                }
            }

            Assert.That(violations, Is.Empty, "File-scoped namespaces are not supported by Unity 6.3:\n" + string.Join("\n", violations));
        }

        [Test]
        public void CoreSources_AreCompiledByTheHeadlessTestProject()
        {
            // If this glob ever drifts, the CI suite would silently stop covering Core.
            string testProject = File.ReadAllText(
                Path.Combine(RepositoryLayout.Root, "Tests", "Armada.Core.Tests", "Armada.Core.Tests.csproj"));

            Assert.That(testProject, Does.Contain("../../Assets/Scripts/Core/**/*.cs"));
            Assert.That(testProject, Does.Contain("../../Assets/Scripts/Core.Tests/**/*.cs"));
        }

        [Test]
        public void CoreSources_AreNotEmpty()
        {
            Assert.That(RepositoryLayout.CoreSourceFiles.Count, Is.GreaterThan(0));
            Assert.That(Directory.GetFiles(RepositoryLayout.CoreTestsSourceDirectory, "*.cs").Length, Is.GreaterThan(0));
        }
    }
}
